[package]
name = 'substrate-validator-set'
version = '1.1.0'
authors = ['Gautam Dhameja <quasijatt@outlook.com>']
edition = '2021'
license = 'Apache-2.0'
repository = 'https://github.com/gautamdhameja/substrate-validator-set'

[dependencies.sp-core]
default-features = false
git = 'https://github.com/paritytech/polkadot-sdk.git'
branch = 'stable2407'

[dependencies.sp-io]
default-features = false
git = 'https://github.com/paritytech/polkadot-sdk.git'
branch = 'stable2407'

[dependencies.sp-runtime]
default-features = false
git = 'https://github.com/paritytech/polkadot-sdk.git'
branch = 'stable2407'

[dependencies.sp-std]
default-features = false
git = 'https://github.com/paritytech/polkadot-sdk.git'
branch = 'stable2407'

[dependencies.sp-staking]
default-features = false
git = 'https://github.com/paritytech/polkadot-sdk.git'
branch = 'stable2407'

[dependencies.frame-benchmarking]
default-features = false
git = 'https://github.com/paritytech/polkadot-sdk.git'
optional = true
branch = 'stable2407'

[dependencies.frame-support]
default-features = false
git = 'https://github.com/paritytech/polkadot-sdk.git'
branch = 'stable2407'

[dependencies.frame-system]
default-features = false
git = 'https://github.com/paritytech/polkadot-sdk.git'
branch = 'stable2407'

[dependencies.pallet-session]
default-features = false
features = ['historical']
git = 'https://github.com/paritytech/polkadot-sdk.git'
branch = 'stable2407'

[dependencies.sp-weights]
default-features = false
git = 'https://github.com/paritytech/polkadot-sdk.git'
branch = 'stable2407'

[dev-dependencies.sp-state-machine]
default-features = false
git = 'https://github.com/paritytech/polkadot-sdk.git'
branch = 'stable2407'

[dependencies.scale-info]
default-features = false
features = ['derive', 'serde']
version = '2.11.3'

[dependencies.log]
default-features = false
version = '0.4.22'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '3.6.12'

[dev-dependencies.serde]
features = ['derive']
version = '1.0.205'

[features]
default = ['std']
runtime-benchmarks = ['frame-benchmarking/runtime-benchmarks']
std = [
    'codec/std',
    'frame-benchmarking/std',
    'frame-support/std',
    'frame-system/std',
    'scale-info/std',
    'sp-core/std',
    'sp-io/std',
    'sp-std/std',
    'sp-runtime/std',
    'pallet-session/std',
]
try-runtime = ['frame-support/try-runtime']
